---
- name: Remove old docker repo if it exists
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent
  become: true

- name: Update apt package
  ansible.builtin.apt:
    update_cache: yes

- name: Install necessary packages
  ansible.builtin.apt: 
    name:  
      - ca-certificates
      - curl
    state: present

- name: Ensure keyrings directory exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key to keyrings directory
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    mode: '0644'

- name: Convert GPG key to binary format as APT require binary format
  ansible.builtin.command:
    cmd: "gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg"
  become: true

- name: Get architecture using dpkg
  command: dpkg --print-architecture
  register: dpkg_architecture

- name: Debug arch and release
  ansible.builtin.debug:
    msg: "Arch={{ dpkg_architecture.stdout }}, Release={{ ansible_distribution_release }}"

- name: Add docker repo to apt soruces
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: true

- name: Update apt package cache again
  ansible.builtin.apt:
    update_cache: yes

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
